### PR TITLE
[FIXES #125] fix when package.json main = ‘.’

### LINKED ISSUE #125: Hidden StackOverflow issue (resulting in bug + perf)
`resolve.sync` of a module with a `package.json` containing `main: '.'` will hang for  quite some time, (up to 800ms on my machine) and then return return the correct value...

Steps to reproduce:

```sh
mkdir -p node_modules/evil/
echo '{"main": "."}' > node_modules/evil/package.json
touch node_modules/evil/index.js
```

```js
require('resolve').sync('evil') //  => "path/to/node_modules/evil/index.js"  (but very slow)
```

If the `try/catch` is removed from https://github.com/substack/node-resolve/blob/master/lib/sync.js#L73 you instead get a fun stack overflow

```
> require('.').sync('evil')
RangeError: Maximum call stack size exceeded
    at new fs.Stats (fs.js:133:20)
    at Object.fs.statSync (fs.js:907:18)
    at isFile (/Users/spenner/src/substack/node-resolve/lib/sync.js:14:27)
    at loadAsFileSync (/Users/spenner/src/substack/node-resolve/lib/sync.js:45:13)
    at loadAsDirectorySync (/Users/spenner/src/substack/node-resolve/lib/sync.js:68:29)
    at loadAsDirectorySync (/Users/spenner/src/substack/node-resolve/lib/sync.js:70:29)
    at loadAsDirectorySync (/Users/spenner/src/substack/node-resolve/lib/sync.js:70:29)
    at loadAsDirectorySync (/Users/spenner/src/substack/node-resolve/lib/sync.js:70:29)
    at loadAsDirectorySync (/Users/spenner/src/substack/node-resolve/lib/sync.js:70:29)
    at loadAsDirectorySync (/Users/spenner/src/substack/node-resolve/lib/sync.js:70:29)
```

### PR DESCRIPTION
**Pull request by stefanpenner**
more details: https://github.com/substack/node-resolve/issues/125

---

In general I would prefer to get rid of that `try/catch` entirely, but doing so and keeping semver will require a more careful approach.

### CODE REVIEW

File: lib/sync.js [hunk 1]
```diff
@@ -64,6 +64,11 @@ module.exports = function (x, options) {
                     pkg = opts.packageFilter(pkg, x);
                 }
 
+                if (pkg.main === '.') {
+                    var i = loadAsFileSync(path.resolve(x, '/index'));
+                    if (i) { return i; }
+                }
+
                 if (pkg.main) {
                     var m = loadAsFileSync(path.resolve(x, pkg.main));
```
Comment (ljharb) [inline lib/sync.js]: i feel like `pkg.main === '.' ? './index' : pkg.main` here might be simpler than the separate `if` statement - also, what happens if `.` is a directory and not a file? ie, let's say there's `./index/index.js` for some reason?

Maybe inside this if, we should `var main = pkg.main === '.' ? './index' : pkg.main;` and use `main` on both the m and n lines?

**Comment by stefanpenner** [comment]
@ljharb I've made some updates:

* mimic'd the `async` feature more closely (explicitly rewrite `pkg.main` for both `.` and './`
* added tests for but sync and async
* included `var body = readFileSync(pkgfile, 'utf8');` within the `try/catch` to more closely mimic the `async` version

**Comment by ljharb** [comment]
Thanks!
