### PR TITLE
[Fix] correctly resolve dir paths when file with the same name exists

### LINKED ISSUE #51: node-resolve incorrectly resolves module-paths like "./someFolder/" when there is a file of the same name
I have a situation (real-world, this exists in the http-proxy module), where the following two things are in the same directory:

http-proxy.js - a file
http-proxy - a folder containing an 'index.js' file

http-proxy.js contains  `require('./http-proxy/')`, which node.js resolves to `./http-proxy/index.js`. `node-resolve` on the other hand, incorrectly resolves it to `./http-proxy.js`.

### PR DESCRIPTION
**Pull request by kamilogorek**
The current behavior is not in line with node's implementation.

```js
require.resolve('./foo') // 'foo.js'
require.resolve('./foo/') // 'foo/index.js'

resolve.sync('./foo') // 'foo.js'
resolve.sync('./foo/') // 'foo.js'
```

It affects both, sync and async methods and I fixed both of them.

Related Jest issue with more details https://github.com/facebook/jest/issues/3199

Fixes #51. Closes #53.

### CODE REVIEW

File: lib/async.js [hunk 1]
```diff
@@ -34,7 +34,7 @@ module.exports = function resolve(x, options, callback) {
 
     if (/^(?:\.\.?(?:\/|$)|\/|([A-Za-z]:)?[/\\])/.test(x)) {
         var res = path.resolve(y, x);
-        if (x === '..') res += '/';
+        if (x === '..' || x[x.length - 1] === '/') res += '/';
```
Comment (ljharb) [inline lib/async.js]: indexing into strings doesn't work in IE 6-8 (it crashes pretty hard) - i'd prefer to use `.slice(-1)` or `.charAt(x.length - 1)` here.

File: lib/sync.js [hunk 2]
```diff
@@ -27,7 +27,7 @@ module.exports = function (x, options) {
 
     if (/^(?:\.\.?(?:\/|$)|\/|([A-Za-z]:)?[/\\])/.test(x)) {
         var res = path.resolve(y, x);
-        if (x === '..') res += '/';
+        if (x === '..' || x[x.length - 1] === '/') res += '/';
```
Comment (ljharb) [inline lib/sync.js]: also here

File: test/resolver_sync.js [hunk 3]
```diff
@@ -204,3 +204,12 @@ test('#79 - re-throw non ENOENT errors from stat', function (t) {
     t.end();
 });
 
+test('#52 - incorrectly resolves module-paths like "./someFolder/" when there is a file of the same name', function (t) {
+    var dir = path.join(__dirname, 'resolver');
+
+    t.equal(
+        resolve.sync('./foo/', { basedir: path.join(dir, 'same_names') }),
```
Comment (ljharb) [inline test/resolver_sync.js]: could we also add a test for `./foo`, to ensure that that ends up with `foo.js`?

File: test/resolver.js [hunk 4]
```diff
@@ -278,3 +278,14 @@ test('#25: node modules with the same name as node stdlib modules', function (t)
         t.equal(res, path.join(resolverDir, 'node_modules/punycode/index.js'));
     });
 });
+
+test('#52 - incorrectly resolves module-paths like "./someFolder/" when there is a file of the same name', function (t) {
+    t.plan(1);
+
+    var dir = path.join(__dirname, 'resolver');
+
+    resolve('./foo/', { basedir: path.join(dir, 'same_names') }, function (err, res, pkg) {
```
Comment (ljharb) [inline test/resolver.js]: could we also add a test for `./foo`, to ensure that resolves to `foo.js`?

**Comment by kamilogorek** [comment]
@ljharb updated all 4 requests :)
